version: '3.7'

services:
  nginx_broadway_demo:
    container_name: nginx_broadway_demo
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dynamodb
    links:
      - php_fpm_broadway_demo
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID='not-a-real-key'
      - AWS_SECRET_ACCESS_KEY='@@not-a-real-secret'
      - REGION='eu-west-1'

  php_fpm_broadway_demo:
    container_name: php_fpm_broadway_demo
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/web
    depends_on:
      - dynamodb
    links:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID='not-a-real-key'
      - AWS_SECRET_ACCESS_KEY='@@not-a-real-secret'
      - REGION='eu-west-1'

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    expose:
      - 8000

  #dynamodb:
    #  container_name: dynamodb
    #  hostname: dynamodb
    #  image: amazon/dynamodb-local:latest
      #  ports:
    #    - 8000:8000
      #  expose:
    #   - 8000
      # networks:
        #   internal_net:
    #     ipv4_address: 172.28.1.1
    # command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
